services:
  issueboardwebserver:
    build:
      context: ./IssueBoardWebServer
    ports:
      - "8080:8080"
    networks:
      - internal-network

  issueboardbackend:
    build:
      context: ./IssueBoardBackend
    ports:
      - "8081:8080"
    networks:
      - internal-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://issue_board:3306/issue_board
      - SPRING_DATASOURCE_USERNAME=myuser
      - SPRING_DATASOURCE_PASSWORD=secret
    depends_on:
      issue_board:
        condition: service_healthy

  #Datenbank
  issue_board:
    image: "mysql:latest"
    ports:
      - 3306:3306
    environment:
      - "MYSQL_DATABASE=issue_board"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=verysecret"
      - "MYSQL_USER=myuser"
    volumes:
      - ./IssueBoardDB/initdb/User.sql:/docker-entrypoint-initdb.d/User.sql

    networks:
      - internal-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 5s
      timeout: 3s
      retries: 10


networks:
  internal-network:
    driver: bridge