services:
  issueboardwebserver:
    build:
      context: ./IssueBoardWebServer
    ports:
      - "8080:8080"
    networks:
      - internal-network

  issueboardbackend:
    build:
      context: ./IssueBoardBackend
    ports:
      - "8081:8080"     
    networks:
      - internal-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://google/issue_board?cloudSqlInstance=braided-facet-447714-a7:europe-west9:issueboard-db&socketFactory=com.google.cloud.sql.mysql.SocketFactory
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=EricJürgenJan
      - GOOGLE_APPLICATION_CREDENTIALS=/app/config/issueboard-service-account-key.json
    volumes:
      - ./config/issueboard-service-account-key.json:/app/config/issueboard-service-account-key.json
    depends_on:
      - issueboardwebserver

  
      
networks:
  internal-network:
    driver: bridge
