name: Docker Build and Deploy

on:
  push:
    branches:
      - "6-github-actions"
  pull_request:
    branches:
      - "6-github-actions"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker images
        run: |
          docker build -t issueboardwebserver ./IssueBoardWebServer
          docker build -t issueboardbackend ./IssueBoardBackend

      - name: Start Compose
        run: docker compose up --build -d

      - name: Health check
        run: |
          sleep 20 
          curl -f http://localhost:8080 || (echo "Frontend failed to start" && exit 1)
          curl -f http://localhost:8081 || (echo "Backend failed to start" && exit 1)

      - name: Stop Compose
        run: docker compose down
