name: Docker Build and Deploy

on:
  push:
    branches:
      - "6-github-actions"
  pull_request:
    branches:
      - "6-github-actions"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      - name: Build and push Docker images
        run: |
          docker-compose -f compose.yaml build
          docker-compose -f compose.yaml up -d

      - name: Run tests in Docker containers
        run: |
          docker-compose -f compose.yaml exec issueboardbackend ./runTests.sh

      - name: Shutdown Docker containers
        run: |
          docker-compose -f compose.yaml down
